service: serverless-example

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-southeast-1
  profile: serverless-deploy2

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

plugins:
  - serverless-offline